### ISSUE TITLE
joy qolib ketgan

### ISSUE THREAD

**Issue by wtfAbduraim** [ismailovquvonchbek/vintilyator#1]
https://github.com/ismailovquvonchbek/vintilyator/blob/58ffb34a32151928f19e51ccfa3a39941f02f84c/index.html#L17C1-L19C1
salom

**Comment by ismailovquvonchbek** [comment]
To'girlab qoyaman raxmat

**Comment by wtfAbduraim** [comment]
etiborli bolaman
